/* Generated By:JavaCC: Do not edit this line. AnalsisLexicoConstants.java */
package Practica2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalsisLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tCOMENTARIO = 1;
  /** RegularExpression Id. */
  int MAS = 6;
  /** RegularExpression Id. */
  int MENOS = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int MUL = 9;
  /** RegularExpression Id. */
  int tPROGRAMA = 10;
  /** RegularExpression Id. */
  int tFINPROGRAMA = 11;
  /** RegularExpression Id. */
  int tVAR = 12;
  /** RegularExpression Id. */
  int tAND = 13;
  /** RegularExpression Id. */
  int tOR = 14;
  /** RegularExpression Id. */
  int tNOT = 15;
  /** RegularExpression Id. */
  int tPRINCIPIO = 16;
  /** RegularExpression Id. */
  int tFIN = 17;
  /** RegularExpression Id. */
  int tSI = 18;
  /** RegularExpression Id. */
  int tENT = 19;
  /** RegularExpression Id. */
  int tSI_NO = 20;
  /** RegularExpression Id. */
  int tFSI = 21;
  /** RegularExpression Id. */
  int tMQ = 22;
  /** RegularExpression Id. */
  int tFMQ = 23;
  /** RegularExpression Id. */
  int tESCRIBIR = 24;
  /** RegularExpression Id. */
  int tLEER = 25;
  /** RegularExpression Id. */
  int tMOD = 26;
  /** RegularExpression Id. */
  int tDIV = 27;
  /** RegularExpression Id. */
  int tENTERO = 28;
  /** RegularExpression Id. */
  int tBOOLEANO = 29;
  /** RegularExpression Id. */
  int tCARACTER = 30;
  /** RegularExpression Id. */
  int tTRUE = 31;
  /** RegularExpression Id. */
  int tFALSE = 32;
  /** RegularExpression Id. */
  int tENTACAR = 33;
  /** RegularExpression Id. */
  int tCARAENT = 34;
  /** RegularExpression Id. */
  int tACCION = 35;
  /** RegularExpression Id. */
  int tVAL = 36;
  /** RegularExpression Id. */
  int tREF = 37;
  /** RegularExpression Id. */
  int tMAYOR = 38;
  /** RegularExpression Id. */
  int tMENOR = 39;
  /** RegularExpression Id. */
  int tIGUAL = 40;
  /** RegularExpression Id. */
  int tMAI = 41;
  /** RegularExpression Id. */
  int tMEI = 42;
  /** RegularExpression Id. */
  int tNI = 43;
  /** RegularExpression Id. */
  int tOPAS = 44;
  /** RegularExpression Id. */
  int tCONSTENTERA = 45;
  /** RegularExpression Id. */
  int tCONSTCHAR = 46;
  /** RegularExpression Id. */
  int tCONSTCAD = 47;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<tCOMENTARIO>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"programa\"",
    "\"finprograma\"",
    "\"var\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"principio\"",
    "\"fin\"",
    "\"si\"",
    "\"ent\"",
    "\"si_no\"",
    "\"fsi\"",
    "\"mq\"",
    "\"fmq\"",
    "\"escribir\"",
    "\"leer\"",
    "\"mod\"",
    "\"div\"",
    "\"entero\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"true\"",
    "\"false\"",
    "\"entacar\"",
    "\"caraent\"",
    "\"accion\"",
    "\"val\"",
    "\"ref\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\":=\"",
    "<tCONSTENTERA>",
    "<tCONSTCHAR>",
    "<tCONSTCAD>",
    "<tIDENTIFICADOR>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
